{% set name = "metadata-inspector" %}
{% set version = "2022.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/metadata_inspector-{{ version }}.tar.gz
  sha256: 4ee21e3e4dc694aa6609bd47f81b1913dae21102c60176cc8a3fedc49552e172

build:
  entry_points:
    - metadata-inspector = metadata_inspector:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cftime
    - dask-core
    - h5netcdf
    - hurry.filesize
    - netcdf4
    - python >=3.7
    - cfgrib
    - requests
    - xarray
    - zarr

test:
  imports:
    - metadata_inspector
  commands:
    - pip check
    - metadata-inspector --help
  requires:
    - pip

about:
  home: https://gitlab.dkrz.de/freva/metadata-inspektor.git
  summary: Inspect metadata of weather/climate datasets
  dev_url: https://gitlab.dkrz.de/freva/metadata-inspektor
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
