{% set name = "metadata-inspector" %}
{% set version = "2022.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/metadata_inspector-{{ version }}.tar.gz
  sha256: 4f4f383c906cf64b1e68bc0b532d9c9aa239db056815c1be1c8779d37de17978

build:
  entry_points:
    - metadata-inspector = metadata_inspector:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cftime
    - dask-core
    - h5netcdf
    - hurry.filesize
    - netcdf4
    - numpy
    - python >=3.7
    - pyyaml
    - cfgrib
    - requests
    - xarray
    - zarr

test:
  imports:
    - metadata_inspector
  commands:
    - pip check
    - metadata-inspector --help
  requires:
    - pip

about:
  home: https://gitlab.dkrz.de/freva/metadata-inspektor.git
  summary: Inspect metadata of weather/climate datasets
  dev_url: https://gitlab.dkrz.de/freva/metadata-inspektor
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
